#[================================================================[.rst:
    Copyright (c)2021, Tom Zhao personal. ("TZOpenTools")
    This software is a personal tools project by Tom Zhao.
    Description:
#]================================================================]

SET(TZ_GLOBAL_CONFIGUATION_TYPES "")

IF(TZ_WINDOWS)
    # COMPILE_DEFINITIONS
    SET(TZ_GLOBAL_COMPILE_DEFINITIONS)

    SET(TZ_GLOBAL_COMPILE_DEFINITIONS_DEBUG
        _DEBUG
    )

    SET(TZ_GLOBAL_COMPILE_DEFINITIONS_RELEASE)

    # COMPILE_OPTIONS
    SET(TZ_GLOBAL_COMPILE_OPTIONS)

    # LINK_FLAGS
    SET(TZ_GLOBAL_LINK_FLAGS)
    SET(TZ_GLOBAL_LINK_FLAGS_DEBUG)

IF(TZ_WINDOWS_BUILD_32)
    SET(__TZ_PLAGFORM_GLOBAL_LINK_RELEASE)
ENDIF()

IF(TZ_WINDOWS_BUILD_64)
    SET(__TZ_PLAGFORM_GLOBAL_LINK_RELEASE)
ENDIF()

    SET(TZ_GLOABL_LINK_FLAGS_RELEASE
        ${__TZ_PLAGFORM_GLOBAL_LINK_RELEASE}
    )

ENDIF(TZ_WINDOWS)

IF(TZ_MAC)
    SET(TZ_GLOBAL_COMPILE_DEFINITIONS
        DUMMY_TZ_PLATFORM_MAC
    )

    TZ_TODO()

ENDIF(TZ_MAC)

IF(TZ_UNIX)
    SET(TZ_GLOBAL_COMPILE_DEFINITIONS
        DUMMY_TZ_PLATFORM_UNIX
    )

    TZ_TODO()

ENDIF(TZ_UNIX)

TZ_ADD_CONFIG("Debug" "d")
TZ_ADD_CONFIG("Release" "")

SET(TZ_GLOBAL_OUTPUT_BINDIR ${PROJECT_BINARY_DIR}/bin)
SET(TZ_GLOBAL_OUTPUT_LIBDIR ${PROJECT_BINARY_DIR}/lib)

SET(TZ_GOLBAL_INSTALL_INCDIR include)
SET(TZ_GLOBAL_INSTALL_BINDIR bin)

IF(TZ_WINDOWS)
    SET(TZ_GLOBAL_INSTALL_LIBDIR bin)
    SET(TZ_GLOBAL_INSTALL_ARCHIVEDIR lib)
ELSE(TZ_WINDOWS)
    SET(TZ_GLOBAL_INSTALL_LIBDIR lib)
    SET(TZ_GLOBAL_INSTALL_ARCHIVEDIR lib)
ENDIF(TZ_WINDOWS)

OPTION(TZ_GLOBAL_DYNAMIC "Set  to on to build all library for dynamic linking. Use OFF for static linking" ON)
OPTION(TZ_BUILD_EXAMPLES "Set to build some examples in our project" ON)